[package]
name = "ys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eval = "0.4.3"
regex = "1.11.1"
serde_json = "1.0.132"
ternop = "1.0.1"
yaml-rust2 = "0.9.0"
